[package]
name = "toktok"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
flexi_logger = "0.31.4"
jiff = "0.2.15"
lettre = "0.11.18"
log = "0.4.28"
reqwest = "0.12.22"
tokio = { version = "1.46.1", features = ["rt-multi-thread", "macros"] }
yaml-rust2 = "0.10.3"
