# TODO Create a global notification config, so config in every service is not required
services:
  site.tuamaeaquelaursa5secs:
    interval: 5
    timeout: 10
    configuration:
      type: Web
      domain: 'https://tuamaeaquelaursa.com'
      expected_http_code: 200
    notification:
      type: file
      directory: /tmp/toktok/tuamaeaquelaursa
      # TODO content_type: text
  site.tuamaeaquelaursa10secs:
    interval: 10
    timeout: 10
    configuration:
      type: Web
      domain: 'https://tuamaeaquelaursa.com'
      expected_http_code: 200
    notification:
      type: file
      directory: /tmp/toktok/tuamaeaquelaursa