# TODO: Create a global notification config, so config in every service is not required
services:
  site.tuamaeaquelaursa10secs:
    interval: 5
    timeout: 10
    config:
      type: Web
      domain: 'https://tuamaeaquelaursa.com'
      expected_http_code: 200
    notification:
      type: File,
      directory: /tmp/toktok/tuamaeaquelaursa